# Generated by Django 3.0.7 on 2020-06-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data_privacy_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
