# Generated by Django 3.0.7 on 2020-06-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_data_privacy_agreement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='data_privacy_agreement',
            new_name='accord_de_don_des_données_à_la_recherche_médicale',
        ),
    ]
