# Generated by Django 3.0.7 on 2020-06-18 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PainSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('intesity', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, max_length=2)),
                ('location', models.CharField(choices=[('Lombaire', 'Lombaire'), ('Abdominale', 'Abdominale'), ('Intra-utérine', 'Intra-utérine'), ('Intestinale', 'Intestinale'), ('Digestive', 'Digestive'), ('Plexus', 'Plexus'), ('Aucune', 'Aucune'), ('Autres', 'Autres')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
