# Generated by Django 3.0.7 on 2020-06-18 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0002_auto_20200618_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='painsymptom',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
