# Generated by Django 3.0.7 on 2020-06-18 13:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0003_painsymptom_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painsymptom',
            name='location',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Lombaire', 'Lombaire'), ('Abdominale', 'Abdominale'), ('Intra-utérine', 'Intra-utérine'), ('Intestinale', 'Intestinale'), ('Digestive', 'Digestive'), ('Plexus', 'Plexus'), ('Aucune', 'Aucune'), ('Autres', 'Autres')], default='Aucune', max_length=20),
        ),
    ]
