# Generated by Django 3.0.7 on 2020-06-18 13:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0004_auto_20200618_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painsymptom',
            name='date',
        ),
        migrations.AddField(
            model_name='painsymptom',
            name='time',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Maintenant', 'Maintenant'), ('Hier', 'Hier'), ('Hier Soir', 'Hier Soir'), ('La Nuit Dernière', 'La Nuit Dernière'), ('Ce Matin', 'Ce Matin'), ('Ce Midi', 'Ce Midi'), ('Cet Après-midi', 'Cet Après-midi'), ('Début de Soirée', 'Début de Soirée'), ('Ce Soir', 'Ce Soir'), ('Cette Nuit', 'Cette Nuit')], default='Maintenant', max_length=20),
        ),
    ]
