# Generated by Django 3.0.7 on 2020-06-18 14:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0005_auto_20200618_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painsymptom',
            name='intesity',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='painsymptom',
            name='location',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Lombaire', 'Lombaire'), ('Abdominale', 'Abdominale'), ('Intra-utérine', 'Intra-utérine'), ('Intestinale', 'Intestinale'), ('Digestive', 'Digestive'), ('Plexus', 'Plexus'), ('Aucune', 'Aucune'), ('Autres', 'Autres')], default='Aucune', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='painsymptom',
            name='time',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Maintenant', 'Maintenant'), ('Hier', 'Hier'), ('Hier Soir', 'Hier Soir'), ('La Nuit Dernière', 'La Nuit Dernière'), ('Ce Matin', 'Ce Matin'), ('Ce Midi', 'Ce Midi'), ('Cet Après-midi', 'Cet Après-midi'), ('Début de Soirée', 'Début de Soirée'), ('Ce Soir', 'Ce Soir'), ('Cette Nuit', 'Cette Nuit')], default='Maintenant', max_length=20, null=True),
        ),
    ]
