# Generated by Django 3.0.7 on 2020-06-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0006_auto_20200618_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painsymptom',
            old_name='intesity',
            new_name='intensity',
        ),
    ]
