# Generated by Django 3.0.7 on 2020-06-18 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0007_auto_20200618_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='PainLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='painsymptom',
            name='intensity',
            field=models.CharField(default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='painsymptom',
            name='location',
            field=models.CharField(default='Aucune', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='painsymptom',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
